### ISSUE TITLE
Not running it when I try to open it

### ISSUE THREAD

**Issue by BlazeSilva** [Admiral-Billy/Pokerogue-App#125]
I tried downloading and running PokeRogue Setup and PokeRogue windows, but every time I try to run them it doesn't work. It appears in task manager as a background process.

**Comment by Admiral-Billy** [comment]
I apparently missed this, oops.

Anyways that usually happens when there's some sort of error on startup, but it's hard to pinpoint exactly what the issue could be. If you're tech-inclined, you can launch the exe through command prompt and you'll probably get more information, but beyond that, you can't do much besides trying the typical restart/reinstall/yadda yadda.
