### ISSUE TITLE
Position Bug on Xiaomi 13T HyperOS

### ISSUE THREAD

**Issue by MikuPanda** [Admiral-Billy/Pokerogue-App#126]
There is a bug on HyperOS which doesn't center the Game. You can't play, in either rotation.

Please fix it :/

**Comment by Chazn2** [comment]
Same issue on my Oppo Find X2 Pro, but since today it's been happening on the previous update also.

Sadly unplayable

**Comment by Chazn2** [comment]
![Screenshot_2024-08-17-21-39-05-85_e24bb2268d29b145a4551512760a7a8b](https://github.com/user-attachments/assets/42c29cc0-980a-4321-8839-30988d97893b)

**Comment by theoxyofmorons** [comment]
Hello, I have this same issue too!

My device is the Ayn Odin 2 Mini running Android 13, also 16:9 display. 

i’ve also tried switching from portrait to landscape back and forth and the only thing that happens is when you end up switching back to landscape after being in portrait is that the image changes but now it’s way too close instead of missing 75% of the image :P

![IMG_1254](https://github.com/user-attachments/assets/6a609d54-3735-4140-a2e9-ab5fc4df8528)
![IMG_1255](https://github.com/user-attachments/assets/98bff3ca-1945-4140-ab68-d08bc830b051)
![IMG_1256](https://github.com/user-attachments/assets/18f542dc-6874-439f-92a9-6e59b820ac25)

**Comment by Admiral-Billy** [comment]
I don't have a device that can replicate this, so it's hard for me to test. If anyone wants to test it and give feedback here's an APK with the pull request's fix in place.

It doesn't seem to cause any issues at least for my test devices, so if it fixes the issue then we're good to go. (I have to upload the file as a zip so it's an APK inside of a zip)
[app-debug.zip](https://github.com/user-attachments/files/17074324/app-debug.zip)

**Comment by MikuPanda** [comment]
Fixed Position bug and Performance Problems! But i just installed it, i will test it a bit more :)

**Comment by Admiral-Billy** [comment]
I'll merge it in then later tonight if there doesn't seem to be any problems, although of course let me know if something comes up!
