### ISSUE TITLE
Can't paste login info

### ISSUE THREAD

**Issue by HakimEG** [Admiral-Billy/Pokerogue-App#5]
Trying it out on Mac, and i cant paste my login information.
And since i', using a password manager, it tends to be very tedious to login.

I imagine that could be the case for many others.

**Comment by Admiral-Billy** [comment]
Oh that's a good point; I'll have to check this out to see what I can do.

At the very least, it only affects the first launch right?

**Comment by Admiral-Billy** [comment]
Alright, I pushed an attempted fix. I can't confirm or deny if this is working because the windows version appears to copy/paste just fine already, but let me know if this does the trick for the Mac version!

https://cdn.discordapp.com/attachments/680826925954236509/1231923154465718323/PokeRogue-macOS.zip?ex=6638b8d8&is=662643d8&hm=e1f0231d7f4cfa987534ab4b9bf5c5296f88b920b0f2b9cc5fe8cb6c9c6e2eb5&

(Yes I used discord to upload the file to then link you said file)
