### ISSUE TITLE
Restarting the Linux Application in offline mode does not load save

### ISSUE THREAD

**Issue by niklasprobul** [Admiral-Billy/Pokerogue-App#53]
After restarting the Linux application (Ubuntu 22.04) while in offline mode, the game starts like the first time you open it. 
All settings are reset and the save is not loaded, even though it was imported and played on previously. 

This does not happen on reload (ctrl+r) or reload+clear cache (ctrl+f5). 

This behaviour started after encountering a JavaScript error after the pokedex (ctrl+d) utility failed to open. I did not save the stack trace, but it was along the lines of "object destroyed". The pokedex could not be opened after this, so I restarted the game to try and fix this. After that the error above occurred. 

I did not update the game files since, the issue happens every time.

**Comment by Admiral-Billy** [comment]
I think this is the sorta thing that happens when the app is still open in the background, as only one version of it can read the save files at any given time. Check and see if there's any extra instances of the app open with Linux's task manager, or give it a PC restart and see if that changes anything.

As for the javascript error, I don't exactly know why that one happens, but I've seen it happen occasionally; if you do get the error again let me know and I'll see if I can debug it.

**Comment by niklasprobul** [comment]
Yeah, you were on point, there was still an unkillable process running in the background. 
Thanks a lot! I dont think there is much you can do about this behaviour.
