### ISSUE TITLE
Discord Rich Presence

### ISSUE THREAD

**Issue by IntoComatose** [Admiral-Billy/Pokerogue-App#9]
I'm not entirely sure why, but after the rich day of me downloading the app, which was v1.2.2, my Discord Rich Presence randomly stopped working. 

I'm not sure if intended, but my discord was not automatically recognizing the app, so I added it manually which caused Rich Presence to work initially. But the following days, Discord just has a blank game icon and no rich presence. 

After a few relaunches, I managed to get the app icon to show on my profile, but not above the mute/deafen/settings section, and Rich Presence still will not activate. No idea what I somehow did but it seems to work fine for my friends.

I have also updated to your newest release as well.

**Comment by Admiral-Billy** [comment]
The newest release at least I know won't properly work for a couple days, since it relies on something that hasn't been released yet. If that's something you want fixed, try the release right before the latest!

That being said, I think that manually adding the app causes Discord to not properly pick up on it, and also Discord is known to be kinda buggy in general when it comes to picking up on game activity, so I'm not really too sure if I can fix this one on my end at all.

**Comment by IntoComatose** [comment]
Ohhh, I didn't realize the newest release is relying on something that's currently unavailable. I just grabbed the previous release and Discord grabbed it immediately and it all seems to be going smoothly now.

Thanks for the quick response and help!
